#服务器配置
server:
  port: 8085

#数据库配置
datasource:
  driverName: mysql
  host: 127.0.0.1
  port: 3306
  database: blog
  username: root
  password: 123
  charset: utf8

#文件配置
filePath:
  #路径结尾必须带斜杠
  image: /WEB/top-image/